name: Update Servers

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3.1.0
        # with:
        #   host: ${{ secrets.HOST }}
        #   username: ${{ secrets.USER }}
        #   key: ${{ secrets.SSH_KEY }}
          # passphrase: ${{ secrets.PASSPHRASE }}

      - name: Sync to Server Kenobi
        run: |
          ssh ${{ secrets.HOST }}@${{ secrets.HOST }} -i ${{ secrets.SSH_KEY }} "cd /home/gustavo/testeCICD && git pull origin main"

     # steps:
     #  - name: Check Out Code
     #    uses: actions/checkout@v3.1.0
     #    with:
     #      key: ${{ secrets.SSH_PRIVATE_KEY }}
     #      known_hosts: ${{ secrets.SSH_HOST }}

     #  - name: Sync to Server Kenobi
     #    run: |
     #      # Replace with your synchronization command for Server 1
     #      ssh gustavo@200.144.221.118 "cd /home/gustavo/testeCICD && git pull origin main"

      # - name: Sync to Server Ahsoka
      #   run: |
      #     # Replace with your synchronization command for Server 2
      #     ssh user@server2 "cd /path/to/your/shared/folder && git pull origin main"

      # - name: Sync to Server 3
      #   run: |
      #     # Replace with your synchronization command for Server 3
      #     ssh user@server3 "cd /path/to/your/shared/folder && git pull origin main"
