- name: ssh pipelines
  uses: cross-the-world/ssh-pipeline@master
  env:
    WELCOME: "ssh pipeline"
  with:
    # ssh remote host
    host: ${{ secrets.HOST }}
    # ssh remote port (optional, default is 22)
    port: 
    # ssh remote user
    user: ${{ secrets.USER }}
    # content of ssh private key. ex raw content of ~/.ssh/id_rsa (optional)
    key: ${{ secrets.SSH_KEY }}
    # ssh remote password (optional)
    pass: 
    # connection timeout to remote host (optional, default is 30s)
    connect_timeout: 
  script: |
    echo $WELCOME 
    mkdir -p /home/github/test/test1 &&
    mkdir -p /home/github/test/test2
